services:

  app:
    build: .
    restart: always
    depends_on:
      appDb:
        condition: service_healthy
    environment:
      HTTP_PORT: 8080
      CONNECTION_STRING: golang_db:golang123@tcp(golang-db.cbuoaypgqh0v.us-east-1.rds.amazonaws.com:3306)/golang_db?charset=utf8mb4&parseTime=True&loc=Local
      STORAGE: db
    ports:
      - 8080:8080

  adminer:
    image: adminer
    restart: always
    ports: # host:container
      - 8081:8080